# Generated by Django 5.2.11 on 2026-02-23 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Lettre de motivation')),
                ('resume', models.FileField(upload_to='resumes/%Y/%m/', verbose_name='CV')),
                ('resume_text', models.TextField(blank=True, verbose_name='Texte extrait du CV')),
                ('ai_score', models.FloatField(blank=True, null=True, verbose_name='Score IA')),
                ('ai_analysis', models.TextField(blank=True, verbose_name='Analyse IA')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('reviewed', 'Examinée'), ('interview', 'Entretien planifié'), ('accepted', 'Acceptée'), ('rejected', 'Rejetée')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidature',
                'ordering': ['-ai_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Heure')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu / Lien visio')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='hiring.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entretien',
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('description', models.TextField(verbose_name='Description')),
                ('required_skills', models.TextField(help_text='Séparées par des virgules', verbose_name='Compétences requises')),
                ('contract_type', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('freelance', 'Freelance')], default='cdi', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publiée'), ('paused', 'En pause'), ('closed', 'Clôturée')], default='draft', max_length=20)),
                ('deadline', models.DateField(verbose_name='Date limite')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hiring.jobposting'),
        ),
    ]
