"""nullable_project_dates

Revision ID: 2fe9a1d27553
Revises: 975f58b194f6
Create Date: 2026-03-12 13:42:21.879005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe9a1d27553'
down_revision: Union[str, None] = '975f58b194f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('projects', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
