"""add_project_config

Revision ID: 8716cb29b15f
Revises: 455fe1e0ef62
Create Date: 2026-03-12 14:15:39.055175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8716cb29b15f'
down_revision: Union[str, None] = '455fe1e0ef62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('points_on_time', sa.Integer(), nullable=False),
    sa.Column('points_late', sa.Integer(), nullable=False),
    sa.Column('notify_deadline_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_configs')
    # ### end Alembic commands ###
