"""replace_manager_with_scrum_role

Revision ID: 0cb0ff019d0b
Revises: 784555443858
Create Date: 2026-05-24 15:43:45.620791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cb0ff019d0b'
down_revision: Union[str, None] = '784555443858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    scrumrole = sa.Enum('PRODUCT_OWNER', 'SCRUM_MASTER', 'TEAM_MEMBER', name='scrumrole')
    scrumrole.create(op.get_bind(), checkfirst=True)
    op.add_column('project_members', sa.Column('scrum_role', scrumrole, server_default='TEAM_MEMBER', nullable=False))
    op.drop_constraint('projects_manager_id_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'manager_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('manager_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_manager_id_fkey', 'projects', 'users', ['manager_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_members', 'scrum_role')
    sa.Enum(name='scrumrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
