"""nullable_job_fields

Revision ID: 66b1b4076251
Revises: 2fe9a1d27553
Create Date: 2026-03-12 13:44:21.689054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b1b4076251'
down_revision: Union[str, None] = '2fe9a1d27553'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'deadline',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_postings', 'deadline',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
