"""add order to stories

Revision ID: 784555443858
Revises: c998ab23842b
Create Date: 2026-05-20 16:17:43.811955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784555443858'
down_revision: Union[str, None] = 'c998ab23842b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('order', sa.Integer(), nullable=True))
    op.execute("UPDATE stories SET \"order\" = 0")
    op.alter_column('stories', 'order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'order')
    # ### end Alembic commands ###
