"""make project names unique

Revision ID: ad5b20e7aa2a
Revises: d198d8b95516
Create Date: 2026-04-19 23:07:24.678596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5b20e7aa2a'
down_revision: Union[str, None] = 'd198d8b95516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_projects_name', 'projects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_projects_name', 'projects', type_='unique')
    # ### end Alembic commands ###
