"""add deadline to projects

Revision ID: c998ab23842b
Revises: 2e036f596250
Create Date: 2026-05-16 22:06:07.896201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c998ab23842b'
down_revision: Union[str, None] = '2e036f596250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('deadline', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'deadline')
    # ### end Alembic commands ###
