"""add_ai_suggestions_to_task

Revision ID: d198d8b95516
Revises: c9f1d2e3a4b5
Create Date: 2026-04-18 00:19:54.968326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd198d8b95516'
down_revision: Union[str, None] = 'c9f1d2e3a4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reward_logs', 'reason')
    op.add_column('tasks', sa.Column('ai_suggestions', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'ai_suggestions')
    op.add_column('reward_logs', sa.Column('reason', sa.VARCHAR(length=200), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
