"""add sprint_duration_days to project_config

Revision ID: d83f396276f2
Revises: 8a5d9f6c4b21
Create Date: 2026-04-20 17:04:01.824357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd83f396276f2'
down_revision: Union[str, None] = '8a5d9f6c4b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_configs', sa.Column('sprint_duration_days', sa.Integer(), nullable=False, server_default='14'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_configs', 'sprint_duration_days')
    # ### end Alembic commands ###
