"""remove_task_chat

Revision ID: f551fe08cf50
Revises: e1f2d3c4b5a6
Create Date: 2026-05-02 02:12:17.952903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f551fe08cf50'
down_revision: Union[str, None] = 'e1f2d3c4b5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_messages_task_id_fkey', 'chat_messages', type_='foreignkey')
    op.drop_column('chat_messages', 'task_id')
    op.add_column('tasks', sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('tasks', sa.Column('blocker_reason', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'blocker_reason')
    op.drop_column('tasks', 'is_blocked')
    op.add_column('chat_messages', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_messages_task_id_fkey', 'chat_messages', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
