"""remove_task_sprint_id

Revision ID: fd6de91edb29
Revises: dc3f1e0a885e
Create Date: 2026-04-26 03:12:14.841600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd6de91edb29'
down_revision: Union[str, None] = 'dc3f1e0a885e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_sprint_id_fkey', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'sprint_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('sprint_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tasks_sprint_id_fkey', 'tasks', 'sprints', ['sprint_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
